export const PERMISSIONS = {
  INTERNAL_USER: "fina2.web.internal.user",
  EXTERNAL_USER: "fina2.web.external.user",
  SURVEY_PUBLIC_UPLOAD: "net.fina.survey.upload.public",
  SURVEY_PRIVATE_UPLOAD: "net.fina.survey.upload.private",
  USER_REVIEW: "net.fina.user.review",
  USER_AMEND: "net.fina.user.amend",
  USER_DELETE: "net.fina.user.delete",

  EMS_INSPECTION_REVIEW: "net.fina.ems.inspection.review",
  EMS_INSPECTION_AMEND: "net.fina.ems.inspection.amend",
  EMS_INSPECTION_DELETE: "net.fina.ems.inspection.delete",
  EMS_INSPECTION_TYPE_REVIEW: "net.fina.ems.inspectionType.review",
  EMS_INSPECTION_TYPE_AMEND: "net.fina.ems.inspectionType.amend",
  EMS_INSPECTION_TYPE_DELETE: "net.fina.ems.inspectionType.delete",
  EMS_FOLLOWUP_REVIEW: "net.fina.ems.followup.review",
  EMS_FOLLOWUP_AMEND: "net.fina.ems.followup.amend",
  EMS_FOLLOWUP_DELETE: "net.fina.ems.followup.delete",
  EMS_INSPECTION_COLUMNS_REVIEW: "net.fina.ems.inspection.columns.review",
  EMS_INSPECTION_COLUMNS_AMEND: "net.fina.ems.inspection.columns.amend",
  EMS_INSPECTION_COLUMNS_DELETE: "net.fina.ems.inspection.columns.delete",
  EMS_IMPORT_FILE_REVIEW: "net.fina.ems.import.file.review",
  EMS_IMPORT_FILE_IMPORT: "net.fina.ems.import.file.import",
  EMS_RECOMMENDATION_REVIEW: "net.fina.ems.recommendation.review",
  EMS_FILE_CONFIGURATION_REVIEW: "net.fina.ems.import.configuration.review",
  EMS_FILE_CONFIGURATION_AMEND: "net.fina.ems.import.configuration.amend",
  EMS_FILE_CONFIGURATION_DELETE: "net.fina.ems.import.configuration.delete",
  EMS_FINE_TYPES_REVIEW: "net.fina.ems.sanctionFineType.review",
  EMS_FINE_TYPES_AMEND: "net.fina.ems.sanctionFineType.amend",
  EMS_FINE_TYPES_DELETE: "net.fina.ems.sanctionFineType.delete",
  EMS_SANCTION_AND_RECOMMENDATION_REVIEW: "net.fina.ems.sanctionType.review",
  EMS_SANCTION_AND_RECOMMENDATION_AMEND: "net.fina.ems.sanctionType.amend",
  EMS_SANCTION_AND_RECOMMENDATION_DELETE: "net.fina.ems.sanctionType.delete",
  EMS_FI_EXPORT: "net.fina.ems.fi.export",

  CEMS_INSPECTION_REVIEW: "net.fina.cems.review",
  CATALOG_REVIEW: "net.fina.catalog.item.review",
  ACTIVE_USER_REVIEW: "net.fina.active.users.review",
  SETTINGS: "fina2.security.settings",
  SURVEY_REVIEW: "net.fina.survey.review",
  RETURN_DEFINITION_REVIEW: "fina2.returns.definition.review",
  RETURN_SCHEDULER_REVIEW: "net.fina.return.scheduler.review",
  RETURN_SCHEDULER_AMEND: "net.fina.return.scheduler.amend",
  RETURN_SCHEDULER_DELETE: "net.fina.return.scheduler.delete",
  IMPORT_MANAGER_REVIEW: "net.fina.import.review",
  IMPORT_MANAGER_FILE_REVIEW: "net.fina.dcs.fileReview",
  SCHEDULE_REVIEW: "fina2.returns.schedule.review",
  SCHEDULE_AMEND: "fina2.returns.schedule.amend",
  SCHEDULE_DELETE: "fina2.returns.schedule.delete",
  LEGISLATIVE_DOCUMENT_REVIEW: "net.fina.legislativeDocument.review",
  LEGISLATIVE_DOCUMENT_AMEND: "net.fina.legislativeDocument.amend",
  LEGISLATIVE_DOCUMENT_DELETE: "net.fina.legislativeDocument.delete",
  FAQ_REVIEW: "net.fina.faq.review",
  FAQ_AMEND: "net.fina.faq.amend",
  FEEDBACK_REVIEW: "net.fina.feedback.review",
  FEEDBACK_CATEGORY_AMEND: "net.fina.feedbackCategory.amend",
  FI_REVIEW: "fina2.bank.review",
  FI_AMEND: "fina2.bank.amend",
  FI_DELETE: "fina2.bank.delete",
  MDT_REVIEW: "fina2.metadata.review",
  MDT_AMEND: "fina2.metadata.amend",
  MDT_DELETE: "fina2.metadata.delete",
  REPORTS_REVIEW: "fina2.report.generate",
  REPORTS_AMEND: "fina2.report.amend",

  TOOLS_REVIEW: "net.fina.tool.serviceMonitor",
  AUDIT_LOG_REVIEW: "net.fina.tool.auditTrailLog",
  MAIL_LOG_REVIEW: "net.fina.tool.mailLog",
  RELEASE_MDT_REVIEW: "net.fina.tool.ostRelease",
  MDT_TO_XML: "net.fina.tool.mdtToXml",
  RETURN_TO_XML: "net.fina.tool.returnToXml",
  MDT_GENERATE: "net.fina.tool.mdtGenerator",
  FINA_FILE_DECRYPTION: "net.fina.tool.finaFileDecryption",

  RETURNS_REVIEW: "fina2.returns.review",
  PERIODS_REVIEW: "fina2.periods.review",
  PERIODS_AMEND: "fina2.periods.amend",
  PERIODS_DELETE: "fina2.periods.delete",
  USER_FILE_SPACE_REVIEW: "net.fina.web.userFileRepository",
  RETURN_VERSION_REVIEW: "fina2.returns.version.review",
  RETURN_VERSION_AMEND: "fina2.returns.version.amend",
  RETURN_VERSION_DELETE: "fina2.returns.version.delete",

  CATALOG_IMPORT: "net.fina.catalog.import",
  CATALOG_EXPORT: "net.fina.catalog.export",
  CATALOG_AMEND: "net.fina.catalog.item.amend",
  CATALOG_DELETE: "net.fina.catalog.item.delete",

  FINA_CALENDAR_REVIEW: "net.fina.calendar.review",
  FINA_CALENDAR_AMEND: "net.fina.calendar.amend",
  FINA_CALENDAR_DELETE: "net.fina.calendar.delete",

  FINA_COMMUNICATOR_MESSAGES_DELETE: "net.fina.communicator.messages.delete",
  FINA_COMMUNICATOR_MESSAGES_AMEND: "net.fina.communicator.messages.amend",
  FINA_COMMUNICATOR_NOTIFICATIONS_DELETE:
    "net.fina.communicator.notifications.delete",
  FINA_COMMUNICATOR_NOTIFICATIONS_AMEND:
    "net.fina.communicator.notifications.amend",
  COMMUNICATOR_MESSAGES_REVIEW: "net.fina.communicator.messages.review",
  FINA_NOTIFICATIONS: "net.fina.communicator.notifications.review",
  FINA_NOTIFICATIONS_ACCEPT: "net.fina.communicator.notifications.accept",
  FINA_TRANSLATIONS: "net.fina.i18n.amend",
  DASHBOARD_MANAGER: "net.fina.dashboard.manager",
  COMMUNICATOR_MESSAGES_BOOKMARK_AMEND:
    "net.fina.communicator.messages.bookmarks.amend",
  COMMUNICATOR_MESSAGES_ACCEPT: "net.fina.communicator.messages.accept",
  COMMUNICATOR_MESSAGES_ACCEPT_WITHOUT_ATTACHMENT:
    "net.fina.communicator.messages.acceptWithoutAttachment",
  FINA_COMMUNICATOR_FILE_SIGN: "net.fina.communicator.file.sign",
  FINA_COMMUNICATOR_BOOKMARK_REVIEW:
    "net.fina.communicator.messages.bookmarks.review",

  FINA_REPORT_FOLDER_GENERATE: "fina2.report.folder.generate",
  FINA_REPORT_GENERATE: "fina2.report.generate",
  FINA_FIRST: "net.fina.first.review",
  MENU_MATRIX: "net.fina.menu.matrix",
  DOCUMENT_MANAGEMENT: "net.fina.menu.document.management",
  FIRST_DASHBOARD: "net.fina.menu.first.dashboard",

  FINA_SECURITY_AMEND: "fina2.security.amend",

  FINA_REPORT_SCHEDULE_MANAGER_REVIEW: "fina2.reports.scheduler.manager",
  FINA_STORED_REPORT_VIEW: "fina2.stored.reports.view",
  FINA_STORED_REPORT_DELETE: "fina2.stored.reports.delete",
  FINA_RETURN_DEFINITION_AMEND: "fina2.returns.definition.amend",
  FINA_RETURN_DEFINITION_DELETE: "fina2.returns.definition.delete",
  FINA_REG_GENERATE_TABLE: "fina.returns.reg.table.generation",
  FINA_RETURNS_AMEND: "fina2.returns.amend",
  FINA_RETURNS_DELETE: "fina2.returns.delete",
  FINA_RETURNS_ACCEPT: "fina2.returns.accept",
  FINA_RETURNS_PROCESS: "fina2.returns.process",
  FINA_RETURNS_REJECT: "fina2.returns.reject",
  FINA_RETURNS_RESET: "fina2.returns.reset",

  FINA_LICTYPE_REVIEW: "net.fina.lictype.review",
  FINA_LICTYPE_AMEND: "net.fina.lictype.amend",
  FINA_LICTYPE_DELETE: "net.fina.lictype.delete",
};
