export const PERIOD_TYPE_CHANGE = "PERIOD_TYPE_CHANGE";
export const LOAD_CONFIGURATION_PROCESSING = "LOAD_CONFIGURATION_PROCESSING";
export const LOAD_CONFIGURATION_SUCCESS = "LOAD_CONFIGURATION_SUCCESS";
export const LOAD_CONFIGURATION_FAILURE = "LOAD_CONFIGURATION_FAILURE";
export const CHART_LABEL_VISIBILITY_CHANGE = "CHART_LABEL_VISIBILITY_CHANGE";
