export const LOAD_CATALOG = "LOAD_CATALOG";
export const CHANGE_CATALOG_PAGING_PAGE = "CHANGE_CATALOG_PAGING_PAGE";
export const CHANGE_CATALOG_PAGING_LIMIT = "CHANGE_CATALOG_PAGING_LIMIT";
export const CHANGE_CATALOG_FILTER = "CHANGE_CATALOG_FILTER";
export const CHANGE_CATALOG_ITEM_FILTER = "CHANGE_CATALOG_ITEM_FILTER";
