export const LOAD_FI_BENEFICIARY_TYPE = "LOAD_FI_BENEFICIARY_TYPE";
export const CHANGE_FI_BENEFICIARY_PAGING_LIMIT =
  "CHANGE_FI_BENEFICIARY_PAGING_LIMIT";
export const CHANGE_FI_BENEFICIARY_PAGING_PAGE =
  "CHANGE_FI_BENEFICIARY_PAGING_PAGE";
