export const LOAD_FILEGALPERSON = "LOAD_FILEGALPERSON";
export const CHANGE_FILEGALPERSON_PAGING_PAGE =
  "CHANGE_FILEGALPERSON_PAGING_PAGE";
export const CHANGE_FILEGALPERSON_PAGING_LIMIT =
  "CHANGE_FILEGALPERSON_PAGING_LIMIT";
export const CHANGE_FILEGALPERSON_FILTER = "CHANGE_FILEGALPERSON_FILTER";
export const CHANGE_FILEGALPERSON_ITEM_FILTER =
  "CHANGE_FILEGALPERSON_ITEM_FILTER";
export const IS_FI_LEGAL_PERSONS_LOADING = "FI_LEGAL_PERSONS_LOADING";
export const IS_FI_LEGAL_PERSONS_LIST_LOADING =
  "IS_FI_LEGAL_PERSONS_LIST_LOADING";
