export const LOAD_MANAGEMENTTYPE = "LOAD_MANAGEMENTTYPE";
export const LOAD_FIMANAGEMENT = "LOAD_FIMANAGEMENT";
export const CHANGE_FIMANAGEMENT_PAGING_PAGE =
  "CHANGE_FIMANAGEMENT_PAGING_PAGE";
export const CHANGE_FIMANAGEMENT_PAGING_LIMIT =
  "CHANGE_FIMANAGEMENT_PAGING_LIMIT";
export const CHANGE_FIMANAGEMENT_FILTER = "CHANGE_FIMANAGEMENT_FILTER";
export const CHANGE_FIMANAGEMENT_ITEM_FILTER =
  "CHANGE_FIMANAGEMENT_ITEM_FILTER";
