export const LOAD_FIPHYSYCALPERSON = "LOAD_FIPHYSYCALPERSON";
export const CHANGE_FIPHYSYCALPERSON_PAGING_PAGE =
  "CHANGE_FIPHYSYCALPERSON_PAGING_PAGE";
export const CHANGE_FIPHYSYCALPERSON_PAGING_LIMIT =
  "CHANGE_FIPHYSYCALPERSON_PAGING_LIMIT";
export const CHANGE_FIPHYSYCALPERSON_FILTER = "CHANGE_FIPHYSYCALPERSON_FILTER";
export const CHANGE_FIPHYSYCALPERSON_ITEM_FILTER =
  "CHANGE_FIPHYSYCALPERSON_ITEM_FILTER";
export const IS_FI_PHYSICAL_PERSONS_LOADING = "FI_PHYSICAL_PERSONS_LOADING";
export const IS_FI_PHYSICAL_PERSON_INFO_LOADING =
  "IS_FI_PHYSICAL_PERSON_INFO_LOADING";
export const IS_FI_MANAGEMENT_LOADING = "IS_FI_MANAGEMENT_LOADING";
export const IS_FI_MANAGEMENT_INFO_LOADING = "IS_FI_MANAGEMENT_INFO_LOADING";
export const IS_FI_PERSON_EDIT_CHANGED = "IS_FI_PERSON_EDIT_CHANGED";
export const IS_FI_PERSON_EDIT = "IS_FI_PERSON_EDIT";
