export const SET_NOTIFICATION_WS = "SET_COMMUNICATOR_WS";
export const SEND_NOTIFICATION_TEXT = "SEND_NOTIFICATION_TEXT";
export const HANDLE_RECEIVED_NOTIFICATION = "HANDLE_RECEIVED_NOTIFICATION";
export const SET_NOTIFICATION_COUNT = "SET_NOTIFICATION_COUNT";
