export const CHANGE_RETURNCREATIONSCHEDULE_PAGING_PAGE =
  "CHANGE_RETURNCREATIONSCHEDULE_PAGING_PAGE";
export const CHANGE_RETURNCREATIONSCHEDULE_PAGING_LIMIT =
  "CHANGE_RETURNCREATIONSCHEDULE_PAGING_LIMIT";
