export const CHANGE_USER_PAGING_PAGE = "CHANGE_USER_PAGING_PAGE";
export const CHANGE_USER_PAGING_LIMIT = "CHANGE_USER_PAGING_LIMIT";
export const CHANGE_USER_FILTER = "CHANGE_USER_FILTER";
export const CHANGE_EDIT_MODE = "CHANGE_EDIT_MODE";
export const UPDATE_USER = "UPDATE_USER";
